In [14]:
# needed imports
from matplotlib import pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
import numpy as np

from scipy.cluster.hierarchy import cophenet
from scipy.spatial.distance import pdist


In [5]:
a = np.random.multivariate_normal([10, 0], [[3, 1], [1, 4]], size=[3,])
b = np.random.multivariate_normal([0, 20], [[3, 1], [1, 4]], size=[3,])
X = np.concatenate((a, b),)

In [6]:
X

array([[11.35913538,  2.50934247],
       [ 8.01028038, -0.61946966],
       [ 8.56608835,  1.17810441],
       [ 0.59803537, 19.8287683 ],
       [ 2.90812942, 21.56379875],
       [-2.20495076, 19.30172476]])

In [7]:
Z = linkage(X, 'ward')

In [8]:
Z

array([[ 1.        ,  2.        ,  1.8815406 ,  2.        ],
       [ 3.        ,  5.        ,  2.85210556,  2.        ],
       [ 0.        ,  6.        ,  4.38235128,  3.        ],
       [ 4.        ,  7.        ,  4.86759214,  3.        ],
       [ 8.        ,  9.        , 36.65231935,  6.        ]])

In [31]:
Z2=linkage(A, 'ward')

In [32]:
Z2

array([[1.        , 2.        , 0.42426407, 2.        ],
       [0.        , 3.        , 0.80415587, 3.        ]])

In [33]:
c, coph_dists = cophenet(Z2, pdist(A))

In [34]:
c

0.7673944972175931

In [35]:
from scipy.cluster.hierarchy import fcluster
max_d = 0.2
clusters = fcluster(Z2, max_d, criterion='distance')
clusters

array([3, 1, 2], dtype=int32)

In [36]:
def cluster_matrix(matrix, algorithm='ward', max_d=0.3, criterion='distance'):
    merges = linkage(matrix, 'ward')
    clusters = fcluster(merges, max_d, criterion=criterion)
    return clusters

In [53]:
A = [[1, 0.1, 0.9], 
    [0.1, 1, 0.1],
    [0.9, 0.1, 1]]

In [59]:
invA=np.ones(3)-A

In [57]:
invA

array([[0. , 0.9, 0.1],
       [0.9, 0. , 0.9],
       [0.1, 0.9, 0. ]])

In [71]:
from sklearn.cluster import DBSCAN
labels=DBSCAN(min_samples=1, metric='precomputed', eps=0.3).fit_predict(invA)

n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)
n_noise_ = list(labels).count(-1)

print(n_clusters_, n_noise_)

2 0


In [65]:
a={'a':2, 'b':3}
c={'a2':23, 'b2':13}
a.update(c)

In [66]:
a

{'a': 2, 'b': 3, 'a2': 23, 'b2': 13}

In [67]:
a=a.update(c)

In [68]:
a